# Generated by Django 2.2.2 on 2019-06-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
